!jmb-configuration-v1

name: JMB
outboundEndpoints:
- name: notRouted
  flow:
    name: nullOutboundFlow          
- name: EP
  flow:
    name: httpOutboundFlow
    parameters:
    - name: "path"
      value: "/connect-lpa-api/v1/ingestion"
    - name: "fileName"
      value: "outputMessageWMA.xml"
outboundMappings:
  - receiver: 'EP.POC'
    request: '*:*:*'
    outboundEndpoint: 'EP'
  - receiver: 'NOT.ROUTED'
    request: '*:*:*'
    outboundEndpoint: 'notRouted'
 